# **PREPROCESSING**

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

In [3]:
%ls

In [4]:
%cd /content/drive/MyDrive/Dataset

[Errno 2] No such file or directory: '/content/drive/MyDrive/Dataset'
/kaggle/working


In [5]:
import cv2
import os
import sys
import glob
from tqdm import tqdm

In [6]:
# import os
# from zipfile import ZipFile

# # Define the path to the zip file
# zip_path = '/kaggle/input/your-dataset-folder/your-dataset.zip'
# extract_path = '/kaggle/working/your-dataset'

# # Extract the zip file
# with ZipFile(zip_path, 'r') as zip_ref:
#     zip_ref.extractall(extract_path)

In [7]:
PATH_violence = "/kaggle/input/dataset/Violence-20240519T072356Z-001/Violence"

In [8]:
PATH_nonviolence = "/kaggle/input/dataset/NonViolence-20240519T072357Z-001/NonViolence"

**Frame selection**

In [9]:
# os.makedirs('./data/Violence1',exist_ok=True)

# for path in tqdm(glob.glob(PATH_violence + '/*')):
#     fname = os.path.basename(path).split('.')[0]
#     vidcap = cv2.VideoCapture(path)
#     success, image = vidcap.read()
#     count = 0
#     while success:
#         if count % 10 == 0:
#             cv2.imwrite("./data/Violence/{}-{}.jpg".format(fname, str(count).zfill(4)), image)
#         success, image = vidcap.read()
#         count += 1

In [10]:

# for path in tqdm(glob.glob(PATH_nonviolence + '/*')):
#     fname = os.path.basename(path).split('.')[0]
#     vidcap = cv2.VideoCapture(path)
#     success, image = vidcap.read()
#     count = 0
#     while success:
#         if count % 10 == 0:
#             save_path = f"./data/NonViolence/{fname}-{str(count).zfill(4)}.jpg"
#             cv2.imwrite(save_path, image)
#         success, image = vidcap.read()
#         count += 1

In [11]:
!pip install imutils



In [12]:
!pip install imutils


In [13]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from keras.layers import AveragePooling2D
from imutils import paths
from keras.utils import to_categorical
from sklearn.preprocessing import LabelBinarizer


2024-05-19 14:09:49.277307: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-19 14:09:49.277461: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-19 14:09:49.407752: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [14]:
args = {
    "dataset": "data",
    "model": "model/violence_model.h5",
    "label-bin": "model/lb.pickle",
    "epochs": 10,
    "plot": "plot.png"

}

**Frame resizing**

In [15]:
print('-'*100)
print("[INFO] loading images...")
print('-'*100)
imagePaths = list(paths.list_images(args["dataset"]))
data = []
labels = []

----------------------------------------------------------------------------------------------------
[INFO] loading images...
----------------------------------------------------------------------------------------------------


In [16]:
LABELS = set(["Violence", "NonViolence"])

In [17]:
import os
import cv2
from tqdm import tqdm

# Provided paths
non_violence_path = "/kaggle/input/images/NonViolence/NonViolence"
violence_path = "/kaggle/input/images/Violence/Violence"

# List to store data and labels
data = []
labels = []

# Iterate through NonViolence images
for imagePath in tqdm(os.listdir(non_violence_path)[:5000]):
    image_path = os.path.join(non_violence_path, imagePath)
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (224, 224))
    data.append(image)
    labels.append(0)  # Assigning 0 for NonViolence

# Iterate through Violence images
for imagePath in tqdm(os.listdir(violence_path)[:7000]):
    image_path = os.path.join(violence_path, imagePath)
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (224, 224))
    data.append(image)
    labels.append(1)  # Assigning 1 for Violence


100%|██████████| 7000/7000 [01:19<00:00, 88.25it/s] 


In [18]:
data = np.array(data)
labels = np.array(labels)

In [19]:
lb = LabelBinarizer()
labels = lb.fit_transform(labels)
labels = to_categorical(labels)

In [20]:
print (data)

[[[[129 127 128]
   [129 129 127]
   [127 133 129]
   ...
   [159 160 154]
   [155 156 150]
   [150 151 145]]

  [[123 119 120]
   [119 119 119]
   [115 120 116]
   ...
   [152 153 147]
   [153 154 148]
   [153 154 148]]

  [[127 121 125]
   [123 121 122]
   [120 122 119]
   ...
   [142 143 138]
   [146 147 142]
   [149 150 145]]

  ...

  [[ 73  73  75]
   [ 72  72  74]
   [ 67  67  69]
   ...
   [212 212 214]
   [200 200 202]
   [175 175 177]]

  [[ 61  61  63]
   [ 67  67  69]
   [ 69  69  71]
   ...
   [212 212 214]
   [200 200 202]
   [175 175 177]]

  [[ 66  66  68]
   [ 64  64  66]
   [ 54  54  56]
   ...
   [212 212 214]
   [200 200 202]
   [175 175 177]]]


 [[[ 74 134 148]
   [  6 105 138]
   [ 12  71 110]
   ...
   [ 15  16   9]
   [ 23  21  16]
   [ 27  19  17]]

  [[ 35 115 127]
   [ 19 122 160]
   [ 16  61 105]
   ...
   [ 22  23  17]
   [ 32  30  26]
   [ 39  31  29]]

  [[ 64 111 122]
   [ 29 103 138]
   [  6  32  70]
   ...
   [ 20  21  15]
   [ 35  33  28]
   [ 39  33

In [21]:
print(labels)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]


**Frame augmentation**

In [22]:
trainAug = ImageDataGenerator(
    rotation_range=30,
    zoom_range=0.15,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.15,
    horizontal_flip=True,
    fill_mode="nearest")

In [23]:
valAug = ImageDataGenerator()

In [33]:
import numpy as np
from sklearn.model_selection import train_test_split


# Flatten each image and reshape to 2D array (samples, flattened_size)
data = data.reshape(data.shape[0], -1)

# Split the data into train and test sets
(trainX, testX, trainY, testY) = train_test_split(data, labels, test_size=0.25, stratify=labels, random_state=42)


In [34]:
# !pip install tensorflow-decision-forests==1.8.1 tensorflow-text==2.15.0 tf-keras==2.15.1


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 20.6 MB/s eta 0:00:0000:010:01
  Attempting uninstall: keras
    Found existing installation: keras 3.2.1
    Uninstalling keras-3.2.1:
      Successfully uninstalled keras-3.2.1


In [26]:
# !pip install tensorflow==2.15.0 tensorflow-decision-forests==1.9.1 tensorflow-text==2.16.1 tf-keras==2.16.0 keras-nlp==0.9.3 keras-core==0.5.1 ml-dtypes>=0.3.1


In [46]:
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.applications import InceptionV3
from tensorflow.keras.models import Model
from tensorflow.keras.layers import AveragePooling2D, Flatten, Dense, Dropout, Input
from tensorflow.keras.preprocessing.image import img_to_array
from collections import deque
from tensorflow.keras.layers import Dropout

In [48]:
base_model = InceptionV3(weights="imagenet", include_top=False, input_tensor=Input(shape=(224, 224, 3)))
head_model = base_model.output
head_model = AveragePooling2D(pool_size=(5, 5))(head_model)
head_model = Flatten(name="flatten")(head_model)
head_model = Dense(512, activation="relu")(head_model)
head_model = Dropout(0.5)(head_model)
head_model = Dense(2, activation="softmax")(head_model)

In [49]:
model = Model(inputs=base_model.input, outputs=head_model)

In [50]:
model.trainable = True

In [51]:
opt = SGD(learning_rate=1e-4, momentum=0.9, decay=1e-4 / args["epochs"])
model.compile(loss="categorical_crossentropy", optimizer=opt, metrics=["accuracy"])
print(model.summary())

Model: "functional_14"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_6       │ (None, 224, 224,  │          0 │ -                 │
│ (InputLayer)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_282 (Conv2D) │ (None, 111, 111,  │        864 │ input_layer_6[0]… │
│                     │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 111, 111,  │         96 │ conv2d_282[0][0]  │
│ (BatchNormalizatio… │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_282      │ (None, 111, 111,  │          0 │ batch_normalizat… │
│ (Activation)        │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_283 (Conv2D) │ (None, 109, 109,  │      9,216 │ activation_282[0… │
│                     │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 109, 109,  │         96 │ conv2d_283[0][0]  │
│ (BatchNormalizatio… │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_283      │ (None, 109, 109,  │          0 │ batch_normalizat… │
│ (Activation)        │ 32)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_284 (Conv2D) │ (None, 109, 109,  │     18,432 │ activation_283[0… │
│                     │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 109, 109,  │        192 │ conv2d_284[0][0]  │
│ (BatchNormalizatio… │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_284      │ (None, 109, 109,  │          0 │ batch_normalizat… │
│ (Activation)        │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ max_pooling2d_12    │ (None, 54, 54,    │          0 │ activation_284[0… │
│ (MaxPooling2D)      │ 64)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_285 (Conv2D) │ (None, 54, 54,    │      5,120 │ max_pooling2d_12… │
│                     │ 80)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 54, 54,    │        240 │ conv2d_285[0][0]  │
│ (BatchNormalizatio… │ 80)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_285      │ (None, 54, 54,    │          0 │ batch_normalizat… │
│ (Activation)        │ 80)               │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv2d_286 (Conv2D) │ (None, 52, 52,    │    138,240 │ activation_285[0… │
│                     │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 52, 52,    │        576 │ conv2d_286[0][0]  │
│ (BatchNormalizatio… │ 192)              │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_286      │ (None, 52, 52,    │          0 │ batch_normalizat

 Total params: 22,852,898 (87.18 MB)

 Trainable params: 22,818,466 (87.05 MB)

 Non-trainable params: 34,432 (134.50 KB)

None


In [ ]:

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# # Example dimensions
# height, width, channels = 224, 224, 3

# # Reshape the data
# trainX = trainX.reshape((-1, height, width, channels))
# testX = testX.reshape((-1, height, width, channels))

# print("trainX shape:", trainX.shape)
# print("testX shape:", testX.shape)


# model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

H = model.fit(
    trainAug.flow(trainX, trainY, batch_size=32),
    steps_per_epoch=len(trainX) // 32,
    validation_data=valAug.flow(testX, testY),
    validation_steps=len(testX) // 32,
    epochs=50  
)


In [ ]:
print("[INFO] training head...")
print('-'*100)
H = model.fit(
    trainAug.flow(trainX, trainY, batch_size=32),
    steps_per_epoch=len(trainX) // 32,
    validation_data=valAug.flow(testX, testY),
    validation_steps=len(testX) // 32,
    epochs=args["epochs"])

In [ ]:
model_path = "/content/drive/MyDrive/model/inception_model.h5"
model.save(model_path)

In [ ]:
lstm_model = Sequential([
    LSTM(units=128, return_sequences=True, input_shape=(None, 2048)),  # Increased units and return sequences
    Dropout(0.5),  # Dropout for regularization
    LSTM(units=64),  # Additional LSTM layer for deeper architecture
    Dense(units=32, activation='relu'),  # Additional fully connected layer for feature extraction
    Dropout(0.5),  # Dropout for regularization
    Dense(units=1, activation='sigmoid')  # Output a binary classification (violence or non-violence)
])

In [ ]:
opt = SGD(lr=1e-4, momentum=0.9, decay=1e-4 / args["epochs"])
lstm_model.compile(loss="binary_crossentropy", optimizer=opt, metrics=["accuracy"])
print(lstm_model.summary())

In [ ]:
H = lstm_model.fit_generator(
    trainAug.flow(trainX, trainY, batch_size=32),
    steps_per_epoch=len(trainX) // 32,
    validation_data=valAug.flow(testX, testY),
    validation_steps=len(testX) // 32,
    epochs=args["epochs"]
)

In [ ]:
model_path = "model/lstm_model.h5"
lstm_model.save(model_path)

In [ ]:
import cv2
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt



In [ ]:

def test_violence_detection_on_videos(test_videos):
    true_positives = 0
    total_violence_frames = 0
    total_frames = 0
    predictions = []
    ground_truths = []

    for video_path in test_videos:
        cap = cv2.VideoCapture(video_path)
        frame_count = 0
        frame_buffer = []

        while cap.isOpened():
            ret, frame = cap.read()

            if ret:
                preprocessed_frame = preprocess_frame(frame)
                inception_prediction = inceptionv3_model.predict(preprocessed_frame)

                if inception_prediction >= 0.8:
                    total_violence_frames += 1
                    lstm_prediction = lstm_model.predict(np.array(frame_buffer[-30:]))
                    if lstm_prediction >= 0.5:
                        true_positives += 1

                    predictions.append(1)
                else:
                    predictions.append(0)

                frame_buffer.append(preprocessed_frame)

                if len(frame_buffer) > 30:
                    frame_buffer.pop(0)

                frame_count += 1
                total_frames += 1
            else:
                break

        cap.release()

    accuracy = accuracy_score(ground_truths, predictions)
    precision = precision_score(ground_truths, predictions)
    recall = recall_score(ground_truths, predictions)
    f1 = f1_score(ground_truths, predictions)

    print("Accuracy:", accuracy)
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1 Score:", f1)

    return accuracy, precision, recall, f1


In [ ]:

accuracy, precision, recall, f1 = test_violence_detection_on_videos(test_videos)



In [ ]:


labels = ['Accuracy', 'Precision', 'Recall', 'F1 Score']
metrics = [accuracy, precision, recall, f1]


In [ ]:

plt.figure(figsize=(8, 6))
plt.bar(labels, metrics, color=['blue', 'green', 'red', 'orange'])
plt.title('Violence Detection Performance')
plt.xlabel('Metrics')
plt.ylabel('Score')
plt.ylim(0, 1)
plt.show()

In [ ]:

def test_violence_detection_on_videos():
            true_positives = 0
            total_violence_frames = 0
            total_frames = 0
            predictions = []
            ground_truths = []


            cap = cv2.VideoCapture(video_path)
            frame_count = 0
            frame_buffer = []

            while cap.isOpened():
                ret, frame = cap.read()

                if ret:
                    preprocessed_frame = preprocess_frame(frame)
                    inception_prediction = inceptionv3_model.predict(preprocessed_frame)

                    if inception_prediction >= 0.8:
                        total_violence_frames += 1
                        lstm_prediction = lstm_model.predict(np.array(frame_buffer[-30:]))
                        if lstm_prediction >= 0.5:
                            true_positives += 1

                        predictions.append(1)
                    else:
                        predictions.append(0)

                    frame_buffer.append(preprocessed_frame)

                    if len(frame_buffer) > 30:
                        frame_buffer.pop(0)

                    frame_count += 1
                    total_frames += 1
                else:
                    break

            cap.release()


